// Computes the knowledge-base version: first 12 hex chars of a SHA-256 over the sorted kb/ files
// (docs/specs/05 §2). Written to src/lib/foundry/kb-version.generated.ts and stored on every
// diagnosis and worksheet so results can be traced to the exact content that produced them.
import { createHash } from 'node:crypto'
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const kbDir = path.join(root, 'kb')

const files = existsSync(kbDir)
  ? readdirSync(kbDir).filter((name) => /\.(md|json)$/.test(name)).sort()
  : []

let version = 'no-kb'
if (files.length > 0) {
  const hash = createHash('sha256')
  for (const file of files) hash.update(file).update(readFileSync(path.join(kbDir, file)))
  version = hash.digest('hex').slice(0, 12)
}

writeFileSync(
  path.join(root, 'src', 'lib', 'foundry', 'kb-version.generated.ts'),
  `// GENERATED by scripts/kb-version.mjs. Do not edit by hand.\nexport const KB_VERSION = ${JSON.stringify(version)}\n`,
)
console.log(`kb version: ${version} (${files.length} file(s))`)
