// Bundles prompts/<version>/*.md into src/lib/foundry/prompts.generated.ts so the prompts ship with the app
// (serverless functions have no access to the repository's prompts/ folder at runtime).
// The version comes from prompts/VERSION; changing a prompt means bumping it (docs/specs/05 §3).
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const version = readFileSync(path.join(root, 'prompts', 'VERSION'), 'utf8').trim()
const major = version.split('.').slice(0, 2).join('.')
const dir = path.join(root, 'prompts', `v${major}`)

const system = readFileSync(path.join(dir, 'system.md'), 'utf8').trim()
const modes = {}
for (const file of readdirSync(path.join(dir, 'modes')).filter((name) => name.endsWith('.md')).sort()) {
  modes[file.replace(/\.md$/, '')] = readFileSync(path.join(dir, 'modes', file), 'utf8').trim()
}

const output = `// GENERATED by scripts/prompts-build.mjs from prompts/v${major}/. Do not edit by hand.
export const PROMPT_VERSION = ${JSON.stringify(version)}
export const SYSTEM_PROMPT: string = ${JSON.stringify(system)}
export const MODE_PROMPTS: Record<string, string> = ${JSON.stringify(modes, null, 2)}
`
writeFileSync(path.join(root, 'src', 'lib', 'foundry', 'prompts.generated.ts'), output)
console.log(`Wrote prompts.generated.ts (prompt version ${version}, modes: ${Object.keys(modes).join(', ')})`)
